name: Update Push Count

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-push-count:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Update Push Count
      run: |
        # Calculate the number of pushes (replace with your actual calculation)
        push_count=$(git rev-list --count HEAD)

        # Replace the push count in README.md
        sed -i "s/PUSH_COUNT_PLACEHOLDER/$push_count/" README.md

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
