name: Update Commit Count

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-commit-count:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Fetch total commit count
      id: fetch-commits
      run: |
        response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/bperdija/bperdija")
        total_commits=$(echo "$response" | jq -r .default_branch.commit.committer.total)

        echo "::set-output name=total_commits::$total_commits"

    - name: Update Commit Count in README
      run: |
        # Replace the total commit count in README.md
        sed -i "s/TOTAL_COMMIT_COUNT_PLACEHOLDER/${{ steps.fetch-commits.outputs.total_commits }}/" README.md
